# Generated by Django 5.2.1 on 2025-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='videos_yout_publish_b3fead_idx'), models.Index(fields=['title'], name='videos_yout_title_54ceda_idx'), models.Index(fields=['description'], name='videos_yout_descrip_6074c4_idx')],
            },
        ),
    ]
